Change the polygons and add the httpClient after CodeReview Kilian
XAI-Demonstrator/xai-demonstrator pull request #633
Opened 2022-01-24 07:53 UTC by ddennyd

- make the polygons in the dict to real Polygons
- outsource the generate_random into another module
- add the httpClient to main and api.py

2022-01-24 12:57 UTC, ionicsolutions requested changes
Sieht gut aus, nur die HTTP-Sessions passen noch nicht 100%, siehe Kommentare.

2022-01-24 12:57 UTC, ionicsolutions commented on guess-the-country/country-backend/country/api.py
> +    async with AioHttpClientSession:
Das geht so nicht, die Session wird nicht durchgereicht. Du musst den Session-Kontext (`with ... as ...`) dort aufmachen, wo du ihn auch benutzen möchtest.

2022-01-24 12:57 UTC, ionicsolutions commented on guess-the-country/country-backend/country/streetview/collect.py
> +                            "&location=" + locstring + "&source=outdoor")
Hier sollte dann `with AioHttpClientSession as session: session.get(...)` stehen, d.h. der GET-Request asynchron über `aiohttp` und nicht synchron über `requests` laufen.

2022-01-24 12:59 UTC, ionicsolutions commented on guess-the-country/country-backend/country/streetview/collect.py
> +                            "&location=" + locstring + "&source=outdoor")
Also so wie [hier](https://github.com/XAI-Demonstrator/xai-demonstrator/blob/master/common/backend-utils/xaidemo/tracking/record.py#L101), nur mit `.get()` statt `.post()`

2022-01-25 10:14 UTC, ddennyd commented on guess-the-country/country-backend/country/streetview/collect.py
> +                            "&location=" + locstring + "&source=outdoor")
Vielen Dank! Hat bei mir irgendwie bisschen länger gedauert aber jetzt hab ichs gecheckt! Ist im neuen Commit.

2022-01-25 12:30 UTC, ionicsolutions approved these changes

2022-01-25 13:08 UTC, merged