Add the tracking in main.py, collect data in predict/explain
XAI-Demonstrator/xai-demonstrator pull request #660
Opened 2022-02-02 13:01 UTC by ddennyd

2022-02-02 14:54 UTC, ionicsolutions requested changes

2022-02-02 14:54 UTC, ionicsolutions commented on guess-the-country/country-backend/country/main.py
>  http_client.set_up(app)
```suggestion
tracking.instrument(app)
```

Das sollte hier oben passieren, der `http_client` wird dabei gleich mit initialisiert.

2022-02-02 14:54 UTC, ionicsolutions commented on guess-the-country/country-backend/country/main.py
> +tracking.instrument(app)
```suggestion
```
Das sollte direkt oben passieren

2022-02-02 14:54 UTC, ionicsolutions commented on guess-the-country/country-backend/country/model/predict.py
> +    record_data(key="internal_state", value={"prediction_id": prediction_id, "predicted:class": class_label})
Diese Daten werden schon automatisch mitgeschrieben, sie sind Teil der Antwort, die der Use Case zurückgibt. Du musst auf diese Weise nur Daten tracken, die nicht Teil des Datenverkehrs zwischen Backend und Frontend sind.

2022-02-02 16:28 UTC, ddennyd commented on guess-the-country/country-backend/country/model/predict.py
> +    record_data(key="internal_state", value={"prediction_id": prediction_id, "predicted:class": class_label})
Danke für den Hinweis. Über das Frontend Tracking können wir ja vielleicht morgen reden.

2022-02-02 16:40 UTC, ionicsolutions approved these changes

2022-03-09 17:47 UTC, ionicsolutions approved these changes

2022-03-09 17:54 UTC, merged